/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neopixel.neochat7;

/**
 *
 * @author neopixel
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChatPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        ChatInputWindow = new javax.swing.JTextField();
        DisconnectButton = new javax.swing.JButton();
        ChatWindow = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ExitButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NeoChat");
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        getContentPane().setLayout(null);

        ChatPanel.setBackground(new java.awt.Color(0, 102, 102));
        ChatPanel.setForeground(new java.awt.Color(0, 102, 102));
        ChatPanel.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 204, 255));
        ChatPanel.add(jSeparator1);
        jSeparator1.setBounds(10, 30, 230, 30);

        Logo.setIcon(new javax.swing.ImageIcon("/Users/neopixel/Documents/Skola/Java/NeoChat/Gui-img/neoChatLogo3mini.png")); // NOI18N
        ChatPanel.add(Logo);
        Logo.setBounds(45, 0, 169, 181);

        ChatInputWindow.setBackground(new java.awt.Color(0, 153, 153));
        ChatInputWindow.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        ChatInputWindow.setToolTipText("Chat Input");
        ChatPanel.add(ChatInputWindow);
        ChatInputWindow.setBounds(10, 400, 230, 30);

        DisconnectButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        DisconnectButton.setText("Disconnect");
        DisconnectButton.setToolTipText("");
        ChatPanel.add(DisconnectButton);
        DisconnectButton.setBounds(70, 450, 95, 30);

        ChatWindow.setBackground(new java.awt.Color(0, 102, 102));
        ChatWindow.setBorder(null);
        ChatWindow.setForeground(new java.awt.Color(0, 102, 102));

        jTextArea1.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        ChatWindow.setViewportView(jTextArea1);

        ChatPanel.add(ChatWindow);
        ChatWindow.setBounds(6, 163, 238, 300);

        ExitButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon("/Users/neopixel/Documents/Skola/Java/NeoChat/Gui-img/exit/1x/outline_close_black_24dp.png")); // NOI18N
        ExitButton.setToolTipText("EXIT");
        ChatPanel.add(ExitButton);
        ExitButton.setBounds(220, 4, 20, 20);

        getContentPane().add(ChatPanel);
        ChatPanel.setBounds(0, 0, 250, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChatInputWindow;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JScrollPane ChatWindow;
    private javax.swing.JButton DisconnectButton;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
